import type { NextPage } from 'next'
import Head from 'next/head'

import NavBar from '../Navbar'

const AppLayout: NextPage = ({ children }) => {
  return (
    <>
      <Head>
        <title>KVN2046</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>{children}</main>
    </>
  )
}

export default AppLayout
